### PR TITLE
Detection of degenerate between-class covariance matrix

### LINKED ISSUE #200: fitting `SubspaceLDA models fails.
The existing code for `SubspaceLDA` fails if for a given input matrix and target, the rank of the between-class covariance matrix is less than the number of classes minus one(i.e `rank(Hw) < ncnz-1` ). This is shown by the code below:
```julia
julia> import MultivariateStats

julia> X1 = rand(5, 5);

julia> y1 = [1,2,3,2, 4];

julia> f = MultivariateStats.fit(MultivariateStats.SubspaceLDA, X1, y1)
ERROR: BoundsError: attempt to access 1×1 adjoint(::Matrix{Float64}) with eltype Float64 at index [1:1, 1:3]
Stacktrace:
 [1] throw_boundserror(A::Adjoint{Float64, Matrix{Float64}}, I::Tuple{Base.Slice{Base.OneTo{Int64}}, UnitRange{Int64}})
   @ Base .\abstractarray.jl:691
 [2] checkbounds
   @ .\abstractarray.jl:656 [inlined]
 [3] _getindex
   @ .\multidimensional.jl:838 [inlined]
 [4] getindex
   @ .\abstractarray.jl:1218 [inlined]
 [5] lda_gsvd(Hb::Matrix{Float64}, Hw::Matrix{Float64}, cweights::Vector{Int64})

```

### PR DESCRIPTION
**Pull request by OkonSamuel**
This PR resolves #200. 
It also includes a new exception called `NullMatrixException` which is thrown when a null matrix is detected at run-time. 
Additionally, Efforts have been made to detect the case when the between-class covariance matrix is null (i.e the zero matrix) based on the input to the `fit(SubspaceLDA, ...)` function. For example when the number of classes/labels equals the number of samples, the  resulting between-class covariance matrix is null, since in computing `Hw` there is only one member per class group which is then subtracted from itself when centering the data.
cc. @ablaom @wildart

### CODE REVIEW

File: src/lda.jl [hunk 1]
```diff
@@ -477,30 +477,43 @@ function fit(::Type{SubspaceLDA}, X::AbstractMatrix{T},
     # (essentially, PCA before LDA)
     Uw, Σw, _ = svd(Hw, full=false)
     keep = Σw .> sqrt(eps(T)) * maximum(Σw)
+    count(keep) > 0 || throw(NullMatrixException("within-class covariance matrix is null"))
```
Comment (wildart) [inline src/lda.jl:480]: You may want to use  `error` function, it will throw `ErrorException` with message provided at the function call. I do not think we need a new exception type.

File: src/lda.jl [hunk 2]
```diff
@@ -477,6 +477,7 @@ function fit(::Type{SubspaceLDA}, X::AbstractMatrix{T},
     # (essentially, PCA before LDA)
     Uw, Σw, _ = svd(Hw, full=false)
     keep = Σw .> sqrt(eps(T)) * maximum(Σw)
+    count(keep) > 0 || throw(error("within-class covariance matrix is null"))
```
Comment (wildart) [inline src/lda.jl:480]: `throw` is redundant. `error` call already throws `ErrorException`

**Review by wildart — CHANGES_REQUESTED** [review]
LGTM
